use_frameworks!

target 'SkyBoxUI_Example' do
  pod 'SkyBoxUI', :path => '../'

  target 'SkyBoxUI_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'FBSnapshotTestCase'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
